### ISSUE TITLE
parrot-graphql isn't transpiled properly

### ISSUE THREAD

**Issue by zleight1** [americanexpress/parrot#53]
It looks like the parrot-graphql package is missing a .babelrc because the generated code is es6 with imports and fails in a node environment.

```
import { mockServer } from 'graphql-tools';
       ^
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\zachary\Documents\Git\TipaltiGit\PayerDashboardAngular\Scripts\app\node_modules\parrot-friendly\lib\index.js:13:45)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

To reproduce, just try and require it in a node file and run `node ./file.js`;

**Comment by jgolden17** [comment]
Thanks @zleight1. Are you able to open a PR with the fix?  Otherwise I can take it up later today.

**Comment by anescobar1991** [comment]
@jgolden17 i think it would be better to stop transpiling anything to begin with. What do you think?

**Comment by zleight1** [comment]
#54

**Comment by jgolden17** [comment]
> @jgolden17 i think it would be better to stop transpiling anything to begin with. What do you think?

I like that idea but it would be a breaking change, would it not?  I'm thinking we should move forward with a bug fix on this version and disable transpiling on the next.

**Comment by anescobar1991** [comment]
Its only a breaking change if you stop supporting node versions we already support, so I think you should be able to do it!

I agree that for now let's unblock @zleight1 and get his bug fix in though.
